import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from 'next/link'
import DropdownMenu from "./components/dropdownMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
                  paddingBottom: "100px"
                }}
      >
        {children}
      <header className="flex font-serif fixed bg-[#FFFFFF] inset-x-0 top-0 border-b border-gray h-[100px] items-center justify-center gap-[150px] text-[30px] z-2">
        <Link className="inline-flex items-center hover:bg-gray-100 px-[50px] hover:rounded-[5px] hover:h-[95px]" href="/">Home</Link>
        <DropdownMenu/>
        <Link className="inline-flex items-center hover:bg-gray-100 px-[50px] hover:rounded-[5px] hover:h-[95px]" href="/faq">About Us</Link>
        
      </header>
        <footer className="flex fixed bg-[#FFFFFF] inset-x-0 bottom-0 border-t border-gray h-[75px] items-center justify-center z-2">
          About This Page (MISC)
          <Image
            className="dark:invert absolute right-10"
            src="/message-text-outline.svg"
            alt="message icon"
            width={40}
            height={40}
            priority
          />
       </footer>
      </body>
      
    </html>
  );
}
